services:
  ignition:
    image: inductiveautomation/ignition:latest
    ports:
      - "8088:8088"
      - "8043:8043"
    environment:
      ACCEPT_IGNITION_EULA: "Y"
      IGNITION_EDITION: standard
      GATEWAY_ADMIN_USERNAME: admin
      GATEWAY_ADMIN_PASSWORD: password
      DISABLE_QUICKSTART: true
    volumes:
      - ./ignition:/usr/local/bin/ignition/data/projects
      - ./site-packages:/usr/local/bin/ignition/user-lib/pylib/site-packages
      - ignition-test-data:/usr/local/bin/ignition/data

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: test
    volumes:
      - mariadb-data:/var/lib/mysql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
      MSSQL_PID: Developer
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  ignition-test-data:
  postgres-data:
  mariadb-data:
  sqlserver-data:
